# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      # - name: Run linter game
      #   run: deno lint game

      # - name: Run linter server
      #   run: deno lint server

      # - name: Run linter main
      #   run: deno lint main

      # - name: Run tests
      #   run: deno test -A

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build server
        run: "deno task compile"

      - name: Install Client deps
        run: "npm install"
        working-directory: client

      - name: Build client
        run: "npm run build:ci"
        working-directory: client

      - uses: vimtor/action-zip@v1.2
        with:
          files: client-dist flesh-n-blood.exe
          dest: flesh-n-blood.zip

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      # - name: Check outputs
      #   run: echo ${{ steps.vars.outputs.sha_short }}

      - uses: actions/upload-artifact@v4
        id: upload-step
        with:
          name: flesh-n-blood-${{ steps.vars.outputs.sha_short }}
          path: ${{ github.workspace }}/flesh-n-blood.zip

      - name: Check outputs
        run: echo ${{ steps.upload-step.outputs.artifact-url }}
